project:
  type: website

  preview: 
    port: 5555
    browser: true
    watch-inputs: true
    navigate: true

  render:
    - "*.qmd"
    - "*.md"
    - "!etc/"

  resources:
    - "files/**"
    - "etc/**"

    # Things that need to be at the site root
    - ".htaccess"
    - "LiveSearchSiteAuth.xml"
    - "keybase.txt"
    - "y_key_31e0c4105fc75710.html"

freeze: true
environment:
  QUARTO_DENO_EXTRA_OPTIONS: "--v8-flags=--stack-size=9999,--heap-size=9999,--max-old-space-size=9999,--max-string-length=6073741824"

execute:
  memory: 20G

bibliography: files/bib/references.bib
csl: files/bib/apa.csl

# Metadata stuff
pagetitle: "{{< meta title >}} | Bradley Rentz"
author-meta: "Bradley Rentz"

website:
  title: "Bradley Rentz"
  description: "Bradley Rentz is an applied quantitative researcher with a background in education research, linguistics, and data science."
  favicon: "/files/probability.png"
  site-url: "https://www.bradleyrentz.com"
  repo-url: "https://github.com/rentzb/bradleyrentz-website"

  google-analytics: "G-7GKK619KJ3"

  
  navbar:
    pinned: true

    left:
      - text: "About"
        href: "index.qmd"
      - text: "Blog"
        href: "blog/index.qmd"
      
    right:
      - text: "{{< iconify bi rss size=1.1em title='RSS' >}}"
        href: atom.xml
      - text: "{{< iconify bi github size=1.1em title='GitHub' >}}"
        href: https://github.com/rentzb
        rel: me
      - text: "{{< iconify bi linkedin size=1.1em title='LinkedIn' >}}"
        href: https://www.linkedin.com/in/bradleyrentz
        rel: me
      - text: "{{< iconify academicons inaturalist size=1.1em title='iNaturalist' >}}"
        href: https://www.inaturalist.org/people/bradleyrentz
        rel: me
  
  page-footer:
    left: |
      <span class="faux-block">{{< fa brands creative-commons >}} {{< var years >}} Bradley Rentz</span>
      <span class="faux-block">All content licensed under<br>[{{< fa brands creative-commons >}} {{< fa brands creative-commons-by >}} Creative Commons CC BY 4.0](https://creativecommons.org/licenses/by/4.0/)</span>      
    center: |
      <span class="faux-block">{{< fa brands orcid >}} <strong>ORCID</strong> [{{< var orcid >}}](https://orcid.org/{{< var orcid >}})</span>
    right: |
      <span class="faux-block">Made with {{< fa brands r-project >}} and [Quarto](https://quarto.org/)</span>
      <span class="faux-block">[View the source at {{< fa brands github >}} GitHub]({{< var github-url >}})</span>

format:
  html:
    theme: 
      - html/br.scss
    grid: 
      body-width: 900px
    toc: false
    code-link: true
    anchor-sections: true
    fig-cap-location: margin
    reference-location: margin
    footnotes-hover: true
    highlight-style: monokai
